Repository WishToGraduate/WishToGraduate, pull requests merged in 2023-07, with the labels that each got.

#21 [Feat] #20 - 검색 뷰 구현
  .gitignore
  WishToGraduate/WishToGraduate.xcodeproj/project.pbxproj
  WishToGraduate/WishToGraduate/Application/SceneDelegate.swift
  WishToGraduate/WishToGraduate/Presentation/Home/Model/HomeListModel.swift
  WishToGraduate/WishToGraduate/Presentation/Home/View/HomeListView.swift
  WishToGraduate/WishToGraduate/Presentation/Home/ViewController/HomeViewController.swift
  WishToGraduate/WishToGraduate/Presentation/Search/Model/SearchSection.swift
  WishToGraduate/WishToGraduate/Presentation/Search/ViewController/SearchViewController.swift
Labels: Feat, ☀️쩡이☀️

#25 [Design] #22 - 글 상세보기 뷰 구현
  WishToGraduate/WishToGraduate.xcodeproj/project.pbxproj
  WishToGraduate/WishToGraduate/Presentation/Detail/ViewController/DetailViewController.swift
  WishToGraduate/WishToGraduate/Presentation/Home/Model/LabelStatusModel.swift
  WishToGraduate/WishToGraduate/Presentation/Home/View/BorrowLabel.swift
  WishToGraduate/WishToGraduate/Resource/AssetCatalog/Color.xcassets/grey/textview_grey.colorset/Contents.json
  WishToGraduate/WishToGraduate/Resource/AssetCatalog/Image.xcassets/Profile/examplePhoto.imageset/Contents.json
  WishToGraduate/WishToGraduate/Resource/AssetCatalog/Image.xcassets/Profile/examplePhoto.imageset/examplePhoto.png
  WishToGraduate/WishToGraduate/Resource/AssetCatalog/Image.xcassets/Profile/examplePhoto.imageset/examplePhoto@2x.png
  WishToGraduate/WishToGraduate/Resource/AssetCatalog/Image.xcassets/Profile/examplePhoto.imageset/examplePhoto@3x.png
  WishToGraduate/WishToGraduate/Util/NameSpace/Color.swift
  WishToGraduate/WishToGraduate/Util/NameSpace/Image.swift
Labels: Feat, Design, 🍀두두🍀

#26 [Fix] #24 - 네비게이션 바 뷰로 변경
  WishToGraduate/WishToGraduate.xcodeproj/project.pbxproj
  WishToGraduate/WishToGraduate/Presentation/Home/View/HomeNavigationView.swift
  WishToGraduate/WishToGraduate/Presentation/Home/ViewController/HomeViewController.swift
  WishToGraduate/WishToGraduate/Presentation/Search/View/SearchNavigationView.swift
  WishToGraduate/WishToGraduate/Presentation/Search/ViewController/SearchViewController.swift
Labels: Fix, ☀️쩡이☀️
